package com.shop.main.test

import com.shop.main.domain.model.FooterType

const val TEST_TAG_APP_LOADING = "TEST_TAG_APP_LOADING"
const val TEST_TAG_HOME_LAZY_COLUMN = "TEST_TAG_HOME_LAZY_COLUMN"
const val TEST_TAG_BANNER_CONTENT = "TEST_TAG_BANNER_CONTENT"
const val TEST_TAG_DETAIL_SCREEN = "TEST_TAG_DETAIL_SCREEN"
const val TEST_TAG_SCROLL_SECTION = "TEST_TAG_SCROLL_SECTION"
const val TEST_TAG_HEADER_LINK = "TEST_TAG_HEADER_LINK"
const val TEST_TAG_FOOTER_PREFIX = "FOOTER_"
val TEST_TAG_FOOTER_REFRESH = "$TEST_TAG_FOOTER_PREFIX${FooterType.REFRESH}"

const val TEST_TAG_BRAND = "TEST_TAG_BRAND"
const val TEST_TAG_PRICE = "TEST_TAG_PRICE"
const val TEST_TAG_PRODUCT_CARD = "TEST_TAG_PRODUCT_CARD"
const val TEST_TAG_STYLE_CARD = "TEST_TAG_STYLE_CARD"
